<Project>
  <PropertyGroup>
    <VersionPrefix>1.4.0</VersionPrefix>
    <Version>1.4.0</Version>
    <AssemblyVersion>1.4.0.0</AssemblyVersion>
    <FileVersion>1.4.0.0</FileVersion>
    <InformationalVersion>V1.4.0</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <Deterministic>true</Deterministic>
    <PathMap>$(MSBuildThisFileDirectory)=/_/</PathMap>
  </PropertyGroup>
</Project>
